DROP TABLE LOGS CASCADE CONSTRAINTS;
DROP TABLE CLIENTES CASCADE CONSTRAINTS;
DROP TABLE FORMASDEPAGO CASCADE CONSTRAINTS;
DROP TABLE PEDIDOS CASCADE CONSTRAINTS;
DROP TABLE PEDIDOSARTICULOS CASCADE CONSTRAINTS;
DROP TABLE USUARIOS CASCADE CONSTRAINTS;
DROP TABLE ARTICULOS CASCADE CONSTRAINTS;
DROP TABLE TIPOARTICULO CASCADE CONSTRAINTS;
--------------------------------------------------------
-- Archivo creado  - jueves-diciembre-04-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SEQ_ARTICULOS
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_ARTICULOS"  MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CLIENTES
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_CLIENTES"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence SEQ_TIPO
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_TIPO"  MINVALUE 1 MAXVALUE 99999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence SEQ_USU
--------------------------------------------------------

 CREATE SEQUENCE "SEQ_USU" MINVALUE 2 MAXVALUE 9999 START WITH 2 INCREMENT BY 1 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
 --------------------------------------------------------
--  DDL for Sequence SEQ_LOG
--------------------------------------------------------

 CREATE SEQUENCE "SEQ_LOG" MINVALUE 1 MAXVALUE 999999999 START WITH 1 INCREMENT BY 1 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Table ARTICULOS
--------------------------------------------------------

  CREATE TABLE "ARTICULOS" 
   (	"IDARTICULO" NUMBER, 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"STOCK" NUMBER, 
	"PRECIO" FLOAT(126), 
	"PESO" FLOAT(126), 
	"TIPO" NUMBER, 
	"ELIMINADO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CLIENTES
--------------------------------------------------------

  CREATE TABLE "CLIENTES" 
   (	"IDCLIENTE" NUMBER, 
	"NOMBRE" VARCHAR2(30 BYTE), 
	"APELLIDO1" VARCHAR2(20 BYTE), 
	"APELLIDO2" VARCHAR2(20 BYTE), 
	"DIRECCION" VARCHAR2(30 BYTE), 
	"REFCPPOBLACIONES" NUMBER, 
	"COMUNIDAD" VARCHAR2(60 BYTE), 
	"PROVINCIA" VARCHAR2(60 BYTE), 
	"POBLACION" VARCHAR2(60 BYTE), 
	"TELEFONO1" NUMBER(9,0), 
	"TELEFONO2" NUMBER(9,0), 
	"EMAIL" VARCHAR2(30 BYTE), 
	"ELIMINADO" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FORMASDEPAGO
--------------------------------------------------------

  CREATE TABLE "FORMASDEPAGO" 
   (	"IDFORMAPAGO" NUMBER, 
	"FORMAPAGO" VARCHAR2(100 BYTE), 
	"ACTIVO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PEDIDOS
--------------------------------------------------------

  CREATE TABLE "PEDIDOS" 
   (	"IDPEDIDO" NUMBER, 
	"REFCLIENTE" NUMBER, 
	"REFUSUARIO" NUMBER, 
	"FECHAPEDIDO" DATE, 
	"FECHAENTREGA" DATE, 
	"REFFORMAPAGO" NUMBER, 
	"TOTAL" NUMBER, 
	"PAGADO" NUMBER, 
	"ELIMINADO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PEDIDOSARTICULOS
--------------------------------------------------------

  CREATE TABLE "PEDIDOSARTICULOS" 
   (	"IDPEDIDOARTICULO" NUMBER, 
	"REFPEDIDO" NUMBER, 
	"REFARTICULO" NUMBER, 
	"CANTIDAD" NUMBER, 
	"PRECIOVENTA" FLOAT(126)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TIPOARTICULO
--------------------------------------------------------

  CREATE TABLE "TIPOARTICULO" 
   (	"IDTIPO" NUMBER, 
	"DESCRIPCION" VARCHAR2(50 BYTE), 
	"ELIMINADO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USUARIOS
--------------------------------------------------------

  CREATE TABLE "USUARIOS" 
   (	"IDUSUARIO" NUMBER, 
	"NOMBRE" VARCHAR2(30 BYTE), 
	"PASSW" VARCHAR2(30 BYTE), 
	"ROL" NUMBER, 
	"ELIMINADO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  ------------------------------------------------------
  --  DDL for Table LOGS
  ------------------------------------------------------
  
  CREATE TABLE "LOGS"
  ( "IDLOG" NUMBER,
  "IDUSUARIO" NUMBER,
  "TIPO" CHAR,	
  "DESCRIPCION" VARCHAR2 (69 BYTE),
  "FECHA" VARCHAR2 (30)
  )SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  
  
REM INSERTING into ARTICULOS
SET DEFINE OFF;
Insert into ARTICULOS (IDARTICULO,NOMBRE,STOCK,PRECIO,PESO,TIPO,ELIMINADO) values ('3','Escopeta','7','21','4','1','0');
Insert into ARTICULOS (IDARTICULO,NOMBRE,STOCK,PRECIO,PESO,TIPO,ELIMINADO) values ('1','Rifle','23','34','3','1','0');
Insert into ARTICULOS (IDARTICULO,NOMBRE,STOCK,PRECIO,PESO,TIPO,ELIMINADO) values ('2','Pistola De Portales','2','100','4','1','0');
Insert into ARTICULOS (IDARTICULO,NOMBRE,STOCK,PRECIO,PESO,TIPO,ELIMINADO) values ('4','Camiseta GLaDoS','2','20','1','2','0');
REM INSERTING into CLIENTES
SET DEFINE OFF;
REM INSERTING into FORMASDEPAGO
SET DEFINE OFF;
Insert into FORMASDEPAGO (IDFORMAPAGO,FORMAPAGO,ACTIVO) values ('1','PayPal','1');
Insert into FORMASDEPAGO (IDFORMAPAGO,FORMAPAGO,ACTIVO) values ('2','Contrarreembolso','1');
Insert into FORMASDEPAGO (IDFORMAPAGO,FORMAPAGO,ACTIVO) values ('3','Tarjeta de cr�dito','1');
Insert into FORMASDEPAGO (IDFORMAPAGO,FORMAPAGO,ACTIVO) values ('4','Bitcoin','1');
REM INSERTING into PEDIDOS
SET DEFINE OFF;
REM INSERTING into PEDIDOSARTICULOS
SET DEFINE OFF;
REM INSERTING into TIPOARTICULO
SET DEFINE OFF;
Insert into TIPOARTICULO (IDTIPO,DESCRIPCION,ELIMINADO) values ('1','Armas','0');
Insert into TIPOARTICULO (IDTIPO,DESCRIPCION,ELIMINADO) values ('2','Camisetas','0');
Insert into TIPOARTICULO (IDTIPO,DESCRIPCION,ELIMINADO) values ('3','Torretas','0');
Insert into TIPOARTICULO (IDTIPO,DESCRIPCION,ELIMINADO) values ('4','Cajas','0');
REM INSERTING into USUARIOS
SET DEFINE OFF;
Insert into USUARIOS (IDUSUARIO,NOMBRE,PASSW,ROL,ELIMINADO) values ('1','GLaDOS','U/wCh7BsHOpvd1EGT+rwAQ==','0','0');
REM INSERTING into LOGS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index ARTICULOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ARTICULOS_PK" ON "ARTICULOS" ("IDARTICULO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CLIENTES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CLIENTES_PK" ON "CLIENTES" ("IDCLIENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FORMASDEPAGO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FORMASDEPAGO_PK" ON "FORMASDEPAGO" ("IDFORMAPAGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PEDIDOSARTICULOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PEDIDOSARTICULOS_PK" ON "PEDIDOSARTICULOS" ("IDPEDIDOARTICULO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PEDIDOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PEDIDOS_PK" ON "PEDIDOS" ("IDPEDIDO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TIPOARTICULO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TIPOARTICULO_PK" ON "TIPOARTICULO" ("IDTIPO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index USUARIOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USUARIOS_PK" ON "USUARIOS" ("IDUSUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  --------------------------------------------------------
--  DDL for Index USUARIOS_PK
----------------------------------------------------------

  CREATE UNIQUE INDEX "LOGS_PK" ON "LOGS"("IDLOG")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ARTICULOS
--------------------------------------------------------

  ALTER TABLE "ARTICULOS" MODIFY ("ELIMINADO" NOT NULL ENABLE);
  ALTER TABLE "ARTICULOS" MODIFY ("TIPO" NOT NULL ENABLE);
  ALTER TABLE "ARTICULOS" MODIFY ("PESO" NOT NULL ENABLE);
  ALTER TABLE "ARTICULOS" MODIFY ("PRECIO" NOT NULL ENABLE);
  ALTER TABLE "ARTICULOS" MODIFY ("STOCK" NOT NULL ENABLE);
  ALTER TABLE "ARTICULOS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "ARTICULOS" MODIFY ("IDARTICULO" NOT NULL ENABLE);
  ALTER TABLE "ARTICULOS" ADD CONSTRAINT "ARTICULOS_PK" PRIMARY KEY ("IDARTICULO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CLIENTES
--------------------------------------------------------

  ALTER TABLE "CLIENTES" MODIFY ("ELIMINADO" NOT NULL ENABLE);
  ALTER TABLE "CLIENTES" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "CLIENTES" MODIFY ("PROVINCIA" NOT NULL ENABLE);
  ALTER TABLE "CLIENTES" MODIFY ("TELEFONO1" NOT NULL ENABLE);
  ALTER TABLE "CLIENTES" MODIFY ("POBLACION" NOT NULL ENABLE);
  ALTER TABLE "CLIENTES" MODIFY ("REFCPPOBLACIONES" NOT NULL ENABLE);
  ALTER TABLE "CLIENTES" MODIFY ("DIRECCION" NOT NULL ENABLE);
  ALTER TABLE "CLIENTES" MODIFY ("APELLIDO1" NOT NULL ENABLE);
  ALTER TABLE "CLIENTES" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "CLIENTES" MODIFY ("IDCLIENTE" NOT NULL ENABLE);
  ALTER TABLE "CLIENTES" ADD CONSTRAINT "CLIENTES_PK" PRIMARY KEY ("IDCLIENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FORMASDEPAGO
--------------------------------------------------------

  ALTER TABLE "FORMASDEPAGO" MODIFY ("IDFORMAPAGO" NOT NULL ENABLE);
  ALTER TABLE "FORMASDEPAGO" ADD CONSTRAINT "FORMASDEPAGO_PK" PRIMARY KEY ("IDFORMAPAGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PEDIDOS
--------------------------------------------------------

  ALTER TABLE "PEDIDOS" ADD CONSTRAINT "PEDIDOS_PK" PRIMARY KEY ("IDPEDIDO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PEDIDOS" MODIFY ("ELIMINADO" NOT NULL ENABLE);
  ALTER TABLE "PEDIDOS" MODIFY ("PAGADO" NOT NULL ENABLE);
  ALTER TABLE "PEDIDOS" MODIFY ("TOTAL" NOT NULL ENABLE);
  ALTER TABLE "PEDIDOS" MODIFY ("REFFORMAPAGO" NOT NULL ENABLE);
  ALTER TABLE "PEDIDOS" MODIFY ("FECHAENTREGA" NOT NULL ENABLE);
  ALTER TABLE "PEDIDOS" MODIFY ("FECHAPEDIDO" NOT NULL ENABLE);
  ALTER TABLE "PEDIDOS" MODIFY ("REFUSUARIO" NOT NULL ENABLE);
  ALTER TABLE "PEDIDOS" MODIFY ("REFCLIENTE" NOT NULL ENABLE);
  ALTER TABLE "PEDIDOS" MODIFY ("IDPEDIDO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PEDIDOSARTICULOS
--------------------------------------------------------

  ALTER TABLE "PEDIDOSARTICULOS" MODIFY ("PRECIOVENTA" NOT NULL ENABLE);
  ALTER TABLE "PEDIDOSARTICULOS" MODIFY ("CANTIDAD" NOT NULL ENABLE);
  ALTER TABLE "PEDIDOSARTICULOS" MODIFY ("REFARTICULO" NOT NULL ENABLE);
  ALTER TABLE "PEDIDOSARTICULOS" MODIFY ("REFPEDIDO" NOT NULL ENABLE);
  ALTER TABLE "PEDIDOSARTICULOS" MODIFY ("IDPEDIDOARTICULO" NOT NULL ENABLE);
  ALTER TABLE "PEDIDOSARTICULOS" ADD CONSTRAINT "PEDIDOSARTICULOS_PK" PRIMARY KEY ("IDPEDIDOARTICULO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TIPOARTICULO
--------------------------------------------------------

  ALTER TABLE "TIPOARTICULO" ADD CONSTRAINT "TIPOARTICULO_PK" PRIMARY KEY ("IDTIPO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TIPOARTICULO" MODIFY ("IDTIPO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USUARIOS
--------------------------------------------------------

  ALTER TABLE "USUARIOS" ADD CONSTRAINT "USUARIOS_PK" PRIMARY KEY ("IDUSUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "USUARIOS" MODIFY ("IDUSUARIO" NOT NULL ENABLE);
  --------------------------------------------------------
--  Constraints for Table LOGS
--------------------------------------------------------

  ALTER TABLE "LOGS" ADD CONSTRAINT "LOGS_PK" PRIMARY KEY ("IDLOG")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "LOGS" MODIFY ("IDLOG" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ARTICULOS
--------------------------------------------------------

  ALTER TABLE "ARTICULOS" ADD CONSTRAINT "FK_TIPOATICULOS" FOREIGN KEY ("TIPO")
	  REFERENCES "TIPOARTICULO" ("IDTIPO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CLIENTES
--------------------------------------------------------

  ALTER TABLE "CLIENTES" ADD CONSTRAINT "FK_REFCPPOBLACIONES" FOREIGN KEY ("REFCPPOBLACIONES")
	  REFERENCES "CODIGOSPOSTALESPOBLACIONES" ("IDCODIGOPOSTALPOB") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PEDIDOS
--------------------------------------------------------

  ALTER TABLE "PEDIDOS" ADD CONSTRAINT "FK_REFCLIENTE" FOREIGN KEY ("REFCLIENTE")
	  REFERENCES "CLIENTES" ("IDCLIENTE") ENABLE;
  ALTER TABLE "PEDIDOS" ADD CONSTRAINT "FK_REFFORMAPAGO" FOREIGN KEY ("REFFORMAPAGO")
	  REFERENCES "FORMASDEPAGO" ("IDFORMAPAGO") ENABLE;
  ALTER TABLE "PEDIDOS" ADD CONSTRAINT "FK_REFUSUARIO" FOREIGN KEY ("REFUSUARIO")
	  REFERENCES "USUARIOS" ("IDUSUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PEDIDOSARTICULOS
--------------------------------------------------------

  ALTER TABLE "PEDIDOSARTICULOS" ADD CONSTRAINT "FK_REFPEDIDO" FOREIGN KEY ("REFPEDIDO")
	  REFERENCES "PEDIDOS" ("IDPEDIDO") ENABLE;
  ALTER TABLE "PEDIDOSARTICULOS" ADD CONSTRAINT "REFARTICULO" FOREIGN KEY ("REFARTICULO")
	  REFERENCES "ARTICULOS" ("IDARTICULO") ENABLE;
    --------------------------------------------------------
--  Ref Constraints for Table LOGS
--------------------------------------------------------

  ALTER TABLE "LOGS" ADD CONSTRAINT "FK_REFUSUARIO" FOREIGN KEY ("REFUSUARIO")
	  REFERENCES "USUARIOS" ("IDUSUARIO") ENABLE;

