--------------------------------------------------------
-- Archivo creado  - martes-diciembre-09-2014   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SEQ_ARTICULOS
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_ARTICULOS"  MINVALUE 1 MAXVALUE 99999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CLIENTES
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_CLIENTES"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 22 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_TIPO
--------------------------------------------------------

   CREATE SEQUENCE  "SEQ_TIPO"  MINVALUE 1 MAXVALUE 99999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table PROVEEDORES
--------------------------------------------------------

  CREATE TABLE "PROVEEDORES" 
   (	"IDPROVEEDOR" NUMBER, 
	"NIF" VARCHAR2(9 BYTE), 
	"NOMBRE" VARCHAR2(40 BYTE), 
	"DIRECCION" VARCHAR2(60 BYTE), 
	"POBLACION" VARCHAR2(60 BYTE), 
	"PROVINCIA" VARCHAR2(60 BYTE), 
	"REFCPPOBLACIONES" NUMBER, 
	"TELEFONO" VARCHAR2(9 BYTE), 
	"COMUNIDAD" VARCHAR2(60 BYTE), 
	"ELIMINADO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##SLEEPYADMIN.PROVEEDORES
SET DEFINE OFF;
Insert into PROVEEDORES (IDPROVEEDOR,NIF,NOMBRE,DIRECCION,POBLACION,PROVINCIA,REFCPPOBLACIONES,TELEFONO,COMUNIDAD,ELIMINADO) values ('1','05745874B','Juanjo','Calle Falsa','Ciudad Real','Ciudad Real','10','659874563','Castilla-La Mancha','0');
Insert into PROVEEDORES (IDPROVEEDOR,NIF,NOMBRE,DIRECCION,POBLACION,PROVINCIA,REFCPPOBLACIONES,TELEFONO,COMUNIDAD,ELIMINADO) values ('2','05784942B','Javier','Calle Falsa 2','Ciudad Real','Ciudad Real','10','654785412','Castilla-La Mancha','0');
--------------------------------------------------------
--  DDL for Index PROVEEDORES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROVEEDORES_PK" ON "PROVEEDORES" ("IDPROVEEDOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table PROVEEDORES
--------------------------------------------------------

  ALTER TABLE "PROVEEDORES" ADD CONSTRAINT "PROVEEDORES_PK" PRIMARY KEY ("IDPROVEEDOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "PROVEEDORES" MODIFY ("IDPROVEEDOR" NOT NULL ENABLE);
 
  ALTER TABLE "PROVEEDORES" MODIFY ("NIF" NOT NULL ENABLE);
 
  ALTER TABLE "PROVEEDORES" MODIFY ("NOMBRE" NOT NULL ENABLE);
 
  ALTER TABLE "PROVEEDORES" MODIFY ("DIRECCION" NOT NULL ENABLE);
 
  ALTER TABLE "PROVEEDORES" MODIFY ("POBLACION" NOT NULL ENABLE);
 
  ALTER TABLE "PROVEEDORES" MODIFY ("PROVINCIA" NOT NULL ENABLE);
 
  ALTER TABLE "PROVEEDORES" MODIFY ("REFCPPOBLACIONES" NOT NULL ENABLE);
 
  ALTER TABLE "PROVEEDORES" MODIFY ("TELEFONO" NOT NULL ENABLE);
 
  ALTER TABLE "PROVEEDORES" MODIFY ("COMUNIDAD" NOT NULL ENABLE);
 
  ALTER TABLE "PROVEEDORES" MODIFY ("ELIMINADO" NOT NULL ENABLE);
