CREATE TABLE COMPOSICIONES
(
  IDCOMPOSICION  INTEGER,
  COMPOSICION    VARCHAR2(40 BYTE),
  PRIMARY KEY (IDCOMPOSICION)
);

CREATE TABLE MEDIDAS
(
  IDMEDIDA  INTEGER,
  MEDIDA    VARCHAR2(40 BYTE),
  PRIMARY KEY (IDMEDIDA)
);
CREATE TABLE ARTICULOS
(
  IDARTICULO      INTEGER,
  REFCOMPOSICION  INTEGER,
  REFMEDIDA       INTEGER,
  PRECIO          FLOAT(126),
  ELIMINADO       INTEGER,
  PRIMARY KEY (IDARTICULO)
);

SET DEFINE OFF;
Insert into COMPOSICIONES
   (IDCOMPOSICION, COMPOSICION)
 Values
   (0, 'Colchón Muelles');
Insert into COMPOSICIONES
   (IDCOMPOSICION, COMPOSICION)
 Values
   (1, 'Colchón Viscoelástica');
Insert into COMPOSICIONES
   (IDCOMPOSICION, COMPOSICION)
 Values
   (2, 'Colchón Latex');
Insert into COMPOSICIONES
   (IDCOMPOSICION, COMPOSICION)
 Values
   (3, 'Colchón Enrollado');
COMMIT;

SET DEFINE OFF;
Insert into MEDIDAS
   (IDMEDIDA, MEDIDA)
 Values
   (0, '80 x 180 cm');
Insert into MEDIDAS
   (IDMEDIDA, MEDIDA)
 Values
   (1, '80 x 190 cm');
Insert into MEDIDAS
   (IDMEDIDA, MEDIDA)
 Values
   (2, '80 x 200 cm');
Insert into MEDIDAS
   (IDMEDIDA, MEDIDA)
 Values
   (3, '90 x 180 cm');
Insert into MEDIDAS
   (IDMEDIDA, MEDIDA)
 Values
   (4, '90 x 190 cm');
Insert into MEDIDAS
   (IDMEDIDA, MEDIDA)
 Values
   (5, '90 x 200 cm');
Insert into MEDIDAS
   (IDMEDIDA, MEDIDA)
 Values
   (6, '105 x 180 cm');
Insert into MEDIDAS
   (IDMEDIDA, MEDIDA)
 Values
   (7, '105 x 190 cm');
Insert into MEDIDAS
   (IDMEDIDA, MEDIDA)
 Values
   (8, '105 x 200 cm');
Insert into MEDIDAS
   (IDMEDIDA, MEDIDA)
 Values
   (9, '135 x 180 cm');
Insert into MEDIDAS
   (IDMEDIDA, MEDIDA)
 Values
   (10, '135 x 190 cm');
Insert into MEDIDAS
   (IDMEDIDA, MEDIDA)
 Values
   (11, '135 x 200 cm');
Insert into MEDIDAS
   (IDMEDIDA, MEDIDA)
 Values
   (12, '150 x 180 cm');
Insert into MEDIDAS
   (IDMEDIDA, MEDIDA)
 Values
   (13, '150 x 190 cm');
Insert into MEDIDAS
   (IDMEDIDA, MEDIDA)
 Values
   (14, '150 x 200 cm');
COMMIT;

SET DEFINE OFF;
Insert into ARTICULOS
   (IDARTICULO, REFCOMPOSICION, REFMEDIDA, PRECIO, ELIMINADO)
 Values
   (1, 0, 0, 200, 0);
Insert into ARTICULOS
   (IDARTICULO, REFCOMPOSICION, REFMEDIDA, PRECIO, ELIMINADO)
 Values
   (2, 0, 1, 210, -1);
Insert into ARTICULOS
   (IDARTICULO, REFCOMPOSICION, REFMEDIDA, PRECIO, ELIMINADO)
 Values
   (3, 0, 2, 220, 0);
Insert into ARTICULOS
   (IDARTICULO, REFCOMPOSICION, REFMEDIDA, PRECIO, ELIMINADO)
 Values
   (4, 0, 3, 240, -1);
Insert into ARTICULOS
   (IDARTICULO, REFCOMPOSICION, REFMEDIDA, PRECIO, ELIMINADO)
 Values
   (5, 0, 4, 260, -1);
Insert into ARTICULOS
   (IDARTICULO, REFCOMPOSICION, REFMEDIDA, PRECIO, ELIMINADO)
 Values
   (6, 0, 5, 270, -1);
Insert into ARTICULOS
   (IDARTICULO, REFCOMPOSICION, REFMEDIDA, PRECIO, ELIMINADO)
 Values
   (7, 1, 0, 230, -1);
Insert into ARTICULOS
   (IDARTICULO, REFCOMPOSICION, REFMEDIDA, PRECIO, ELIMINADO)
 Values
   (8, 1, 1, 240, -1);
Insert into ARTICULOS
   (IDARTICULO, REFCOMPOSICION, REFMEDIDA, PRECIO, ELIMINADO)
 Values
   (9, 1, 2, 250, 0);
Insert into ARTICULOS
   (IDARTICULO, REFCOMPOSICION, REFMEDIDA, PRECIO, ELIMINADO)
 Values
   (10, 1, 3, 260, 0);
Insert into ARTICULOS
   (IDARTICULO, REFCOMPOSICION, REFMEDIDA, PRECIO, ELIMINADO)
 Values
   (11, 1, 4, 280, -1);
Insert into ARTICULOS
   (IDARTICULO, REFCOMPOSICION, REFMEDIDA, PRECIO, ELIMINADO)
 Values
   (12, 1, 5, 290, -1);
Insert into ARTICULOS
   (IDARTICULO, REFCOMPOSICION, REFMEDIDA, PRECIO, ELIMINADO)
 Values
   (13, 2, 2, 300, -1);
Insert into ARTICULOS
   (IDARTICULO, REFCOMPOSICION, REFMEDIDA, PRECIO, ELIMINADO)
 Values
   (14, 2, 3, 310, -1);
Insert into ARTICULOS
   (IDARTICULO, REFCOMPOSICION, REFMEDIDA, PRECIO, ELIMINADO)
 Values
   (15, 2, 4, 320, -1);
Insert into ARTICULOS
   (IDARTICULO, REFCOMPOSICION, REFMEDIDA, PRECIO, ELIMINADO)
 Values
   (16, 2, 5, 330, -1);
Insert into ARTICULOS
   (IDARTICULO, REFCOMPOSICION, REFMEDIDA, PRECIO, ELIMINADO)
 Values
   (17, 2, 6, 340, 0);
Insert into ARTICULOS
   (IDARTICULO, REFCOMPOSICION, REFMEDIDA, PRECIO, ELIMINADO)
 Values
   (18, 2, 7, 350, -1);
COMMIT;
